name: aucmaoverseaslatam
static_sites:
- name: frontend
  github:
    repo: victorra1191/aucmaoverseaslatam
    branch: main
    deploy_on_push: true
  source_dir: frontend
  build_command: npm run build
  output_dir: build
  environment_slug: node-js
  envs:
  - key: NODE_ENV
    value: production